### ISSUE TITLE
windows环境下npm run build没生成exe文件。

### ISSUE THREAD

**Issue by FCYXSZY** [ylxmf2005/LLM-Live2D-Desktop-Assitant#1]
重开几次还是，是我环境有问题吗
![image](https://github.com/user-attachments/assets/f69aef49-7135-4b17-81a1-e0dd71f0c1bd)

**Comment by ylxmf2005** [comment]
fixed, 在我的 windows/mac 上 npm run build 可以正常生成 exe/dmg 并运行了。
不过还是推荐使用 npm start，**npm run build 目前仅支持 electron 前端，而 server.py 后端需要单独部署**（建议看看新的 readme）。
